version: '3.0'

services:
  grafana:
    container_name: nline-plotlyjs-panel
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-latest}
    ports:
      - 3000:3000/tcp
    volumes:
      - ./dist:/var/lib/grafana/plugins/nline-plotlyjs-panel
      - ./provisioning:/etc/grafana/provisioning
